theme: "auto" # "dark"
jwt_secret: "insecure_secret"

server:
  port: 9091
  asset_path: "/config/assets/"

log:
  level: "info" # "debug"

authentication_backend:
  refresh_interval: "1m"
  password_reset:
    disable: false
  # If you want to use a local file instead of LDAP
  # file:
  #   path: "/config/users.yml"
  #   password:
  #     algorithm: "argon2id"
  #     iterations: 1
  #     parallelism: 8
  #     memory: 64
  ldap:
    implementation: "custom"
    url: "ldap://lldap:3890"
    timeout: "5s"
    start_tls: false
    base_dn: "dc=example,dc=com"
    additional_users_dn: "OU=people"
    users_filter: "(&({username_attribute}={input})(objectClass=person))"
    username_attribute: "uid"
    mail_attribute: "mail"
    display_name_attribute: "displayName"
    additional_groups_dn: "OU=groups"
    groups_filter: "(&(member={dn})(objectClass=groupOfNames))"
    group_name_attribute: "cn"
    permit_referrals: false
    permit_unauthenticated_bind: false
    user: "CN=admin,ou=people,dc=example,dc=com"
    password: "N7fcHQs1nmgO7v/XkCzzkEUY7jB5FJ0ceG5qJDZVvp5UumcQIgUVyZD2ioOZJjrT"

totp:
  disable: false
  issuer: "example.com"
  algorithm: "SHA1"
  digits: 6
  period: 30
  skew: 1
  secret_size: 32

webauthn:
  disable: false
  timeout: "60s"
  display_name: "EXAMPLE"
  attestation_conveyance_preference: "indirect"
  user_verification: "preferred"

ntp:
  version: 4
  max_desync: "5s"
  disable_startup_check: false
  disable_failure: true

session:
  secret: "insecure_session_secret"
  name: "EXAMPLE"
  domain: "example.com"
  expiration: "1h"
  inactivity: "15m"
  remember_me_duration: "1M"
  redis:
    host: "redis"
    port: 6379
    username: default
    password: "redis-password-here"
    database_index: 0
    maximum_active_connections: 8
    minimum_idle_connections: 0

regulation:
  max_retries: 3
  find_time: "2m"
  ban_time: "5m"

storage:
  encryption_key: "you_must_generate_a_random_string_of_more_than_twenty_chars_and_configure_this"
  local:
    path: /config/db.sqlite

access_control:
  default_policy: deny
  rules:
    - domain: "public.example.com"
      policy: bypass
    - domain: "traefik.example.com"
      policy: one_factor
      subject: 
        - "group:admins"
    - domain: "one.example.com"
      policy: one_factor
      subject: 
        - "group:dev"
    - domain: "two.example.com"
      policy: two_factor
      subject: 
        - "group:sales"

notifier:
  disable_startup_check: true # false 
  # If you don't have an SMPT server avaiable, you can post the email to a file
  # filesystem:
  #   filename: /config/emails.txt
  smtp:
    host: smtp.example.com
    port: 587
    timeout: 15s
    username: authelia@example.com
    password: smtp-password-here
    sender: "Example - Authelia <authelia@example.com>"
    identifier: authelia.example.com
    subject: "[Authelia] {title}"
    startup_check_address: test@authelia.com
    disable_require_tls: false
    disable_starttls: false
    disable_html_emails: false
